name: oxford_pet
root: data
download: false
train_ratio: 0.9
num_classes: 37

class_names:
  - Abyssinian
  - Bengal
  - Birman
  - Bombay
  - British_Shorthair
  - Egyptian_Mau
  - Maine_Coon
  - Persian
  - Ragdoll
  - Russian_Blue
  - Siamese
  - Sphynx
  - American_Bulldog
  - American_Pit_Bull_Terrier
  - Basset_Hound
  - Beagle
  - Boxer
  - Chihuahua
  - English_Cocker_Spaniel
  - English_Setter
  - German_Shorthaired
  - Great_Pyrenees
  - Havanese
  - Japanese_Chin
  - Keeshond
  - Leonberger
  - Miniature_Pinscher
  - Newfoundland
  - Pomeranian
  - Pug
  - Saint_Bernard
  - Samoyed
  - Scottish_Terrier
  - Shiba_Inu
  - Staffordshire_Bull_Terrier
  - Wheaten_Terrier
  - Yorkshire_Terrier